### ISSUE TITLE
Структура

### ISSUE THREAD

**Issue by leshabirukov** [Bodigrim/categories-for-programmers#1]
Какая предполагается структура? Просто исходные тексты статей в транке, изображения через ссылки к Бартошу\ на Хабр?

**Comment by Bodigrim** [comment]
Сначала надо перевести тексты Бартоша из HTML в MD. Я закоммитил результаты автоматической конвертации первой части, но их надо доконвертировать руками. Это нужно, чтобы дальше не возиться с форматами и любой желающий мог брать `original.md` и переводить в `translation.md`, сохраняя структуру и форматирование текста.
